#!/usr/bin/env sh
set -e

usage() {
	cat <<EOF
Example: doctopdf [ARGS] FILE_PATH
ARGS:
	-o PATH | --output PATH - define pdf file path. Default: FILE_PATH.pdf
	-f | --force - force pdf regeneration
	-v | --view - open for viewing after generation
EOF
}
usage_err() {
	if ! [ "$1" = "" ]; then
		echo "$1" >&2
	fi
	usage
	exit 1
}

command -v soffice >/dev/null 2>&1 || usage_err "to proceed, install libreoffice with [soffice] command"

view=false
force=false
output=""
doc_path=""
while [ $# -gt 0 ]; do
	case $1 in
		-v | --view)
			view=true
			;;
		-f | --force)
			force=true
			;;
		-o | --output)
			[ "$2" = "" ] && usage_err "Argument not specified"
			output="$2"
			shift
			;;
		*)
			[ "$doc_path" = "" ] && doc_path="$1" || doc_path="$doc_path $1"
			;;
	esac
	shift
done

if [ "$doc_path" = "" ]; then
	usage_err "provide document file path"
elif [ ! -f "$doc_path" ]; then
	usage_err "provided document file does not exist"
fi

doc_as_pdf_name="${doc_path%.*}.pdf"
if [ "$output" = "" ]; then
	pdf_path="$doc_as_pdf_name"
else
	pdf_path="$output"
fi

[ -d "$(dirname "$pdf_path")" ] || usage_err "pdf output directory does not exist"

if [ -d "$pdf_path" ]; then
	usage_err "can't create pdf file since directory with the same name exists"
fi
if [ ! -f "$pdf_path" ] || [ "$force" = true ]; then
	# echo "generating"
	echo "generating pdf..." >&2
	/usr/bin/soffice --convert-to pdf "$doc_path" --outdir "/tmp" >&2
	mv "/tmp/$(basename "$doc_as_pdf_name")" "$pdf_path"
fi

echo "$pdf_path"
[ "$view" = true ] && xdg-open "$pdf_path"
