#!/usr/bin/env sh
set -e

if ! [ -d ~/.local/share/kwin/scripts/karousel ]; then
	cmd kpackagetool6 -t KWin/Script -i ./karousel.tar.gz
fi
cmd kpackagetool6 -t KWin/Script -u ./karousel.tar.gz

if ! [ -d ~/.local/share/plasma/plasmoids/org.kde.globalapplet ]; then
	cmd kpackagetool6 -t Plasma/Applet -i ./org.kde.globalapplet
fi
cmd kpackagetool6 -t Plasma/Applet -u ./org.kde.globalapplet

# write to kwinrc
kwriteconfig6 --file ~/.config/kwinrc --group Desktops --key Number "5"
kwriteconfig6 --file ~/.config/kwinrc --group Desktops --key Rows "1"

kwriteconfig6 --file ~/.config/kwinrc --group Effect-windowview --key TouchBorderActivateAll "6"

kwriteconfig6 --file ~/.config/kwinrc --group Plugins --key karouselEnabled "true"
kwriteconfig6 --file ~/.config/kwinrc --group Plugins --key krohnkiteEnabled "false"
kwriteconfig6 --file ~/.config/kwinrc --group Plugins --key slideEnabled "false"
kwriteconfig6 --file ~/.config/kwinrc --group Plugins --key touchpointsEnabled "true"

kwriteconfig6 --file ~/.config/kwinrc --group Script-karousel --key gapsInnerHorizontal "0"
kwriteconfig6 --file ~/.config/kwinrc --group Script-karousel --key gapsInnerVertical "0"
kwriteconfig6 --file ~/.config/kwinrc --group Script-karousel --key gapsOuterBottom "0"
kwriteconfig6 --file ~/.config/kwinrc --group Script-karousel --key gapsOuterLeft "0"
kwriteconfig6 --file ~/.config/kwinrc --group Script-karousel --key gapsOuterRight "0"
kwriteconfig6 --file ~/.config/kwinrc --group Script-karousel --key gapsOuterTop "0"
kwriteconfig6 --file ~/.config/kwinrc --group Script-karousel --key gestureScroll "true"

kwriteconfig6 --file ~/.config/kwinrc --group Script-krohnkite --key binaryTreeLayoutOrder "0"
kwriteconfig6 --file ~/.config/kwinrc --group Script-krohnkite --key cascadeLayoutOrder "0"
kwriteconfig6 --file ~/.config/kwinrc --group Script-krohnkite --key columnsLayoutOrder "0"
kwriteconfig6 --file ~/.config/kwinrc --group Script-krohnkite --key quarterLayoutOrder "0"
kwriteconfig6 --file ~/.config/kwinrc --group Script-krohnkite --key spiralLayoutOrder "0"
kwriteconfig6 --file ~/.config/kwinrc --group Script-krohnkite --key spreadLayoutOrder "0"
kwriteconfig6 --file ~/.config/kwinrc --group Script-krohnkite --key stackedLayoutOrder "0"
kwriteconfig6 --file ~/.config/kwinrc --group Script-krohnkite --key stairLayoutOrder "0"
kwriteconfig6 --file ~/.config/kwinrc --group Script-krohnkite --key threeColumnLayoutOrder "0"


cmd install -D -m 755 ./applications/net.local.terminal.desktop ~/.local/share/applications/net.local.terminal.desktop
cmd install -D -m 755 ./applications/convert-to-pdf.desktop ~/.local/share/applications/convert-to-pdf.desktop
cmd install -D -m 755 ./applications/open-as-pdf.desktop ~/.local/share/applications/open-as-pdf.desktop
cmd install -D -m 600 ./kglobalshortcutsrc ~/.config/kglobalshortcutsrc
cmd install -D -m 600 ./krunnerrc ~/.config/krunnerrc

cmd sudo install -D -m 755 ./scripts/doctopdf /usr/local/bin/doctopdf
cmd sudo install -D -m 755 ./scripts/chlayout /usr/local/bin/chlayout
cmd sudo install -D -m 644 ./00-keyboard.conf /etc/X11/xorg.conf.d/00-keyboard.conf
