#!/usr/bin/env sh
set -e

usage() {
	cat <<EOF
Example: config $DOTFILES_MODULE_NAME
EOF
}
usage_err() {
	if ! [ "$1" = "" ]; then
		echo "$1" >&2
	fi
	usage
	exit 1
}

while [ $# -gt 0 ]; do
	case $1 in
		*)
			usage_err "Invalid option: $1"
			;;
	esac
	shift
done


cmd install -D -m 644 "$(writetext <<EOF
auth="$HOME/.config/yandex-disk/passwd"
dir="$HOME/Yandex.Disk"
proxy="no"
EOF
)" "$HOME/.config/yandex-disk/config.cfg"
echo "Remember to run yandex-disk setup on your first run. Then run: systemctl --user enable yandex-disk.service"
