#!/usr/bin/env sh
set -e

cd "$DOTFILES_MODULE_TEMP"

tmpfile=$(mktemp) || exit 1
for file in "./files"/*; do
    [ -f "$file" ] || continue
    cat "$file" >> "$tmpfile"
    printf '\n' >> "$tmpfile"
done

cmd sudo install -D -m 644 "$tmpfile" /etc/hosts

