#!/usr/bin/env sh

cmd sudo install -D -m 644 ./mic-fix.service /etc/systemd/user/mic-fix.service
cmd systemctl --user enable --now mic-fix.service
cmd install -D -m 644 ./99-mic-denoised.conf ~/.config/pipewire/pipewire.conf.d/99-mic-denoised.conf
