#!/usr/bin/env sh
set -e

usage() {
	cat <<EOF
Example: config $DOTFILES_MODULE_NAME
EOF
}
usage_err() {
	[ "$1" ] && echo "$1" >&2
	usage
	exit 1
}

while [ $# -gt 0 ]; do
	case $1 in
		*)
			usage_err "Invalid option: $1"
			;;
	esac
	shift
done

cmd sudo install -D -m 644 "$(writetext <<EOF
# no fan control, but same chip
options it87 ignore_resource_conflict=1 force_id=0x8689

# fan control works with this, but different chip
# options it87 ignore_resource_conflict=1  force_id=0x8628
EOF
)" /etc/modprobe.d/it87.conf

cmd sudo install -D -m 644 "$(writetext <<EOF
it87
EOF
)" /etc/modules-load.d/it87.conf

cmd sudo systemctl enable lm_sensors.service

