#!/usr/bin/env sh
set -e

usage() {
	cat <<EOF
Example: config $DOTFILES_MODULE_NAME
EOF
}
usage_err() {
	[ "$1" ] && echo "$1" >&2
	usage
	exit 1
}

while [ $# -gt 0 ]; do
	case $1 in
		--cuda)
			cuda=1
			;;
		*)
			usage_err "Invalid option: $1"
			;;
	esac
	shift
done

if [ "$cuda" = "1" ]; then
	cmd install_pkgs cuda
fi

cmd systemctl enable --user app-dev.lizardbyte.app.Sunshine.service

cmd install -D -m 644 ./sunshine.conf ~/.config/sunshine/sunshine.conf
cmd install -D -m 644 "$(writetext <<EOF
{
    "apps": [
        {
            "auto-detach": true,
            "cmd": "",
            "detached": [
                "$DOTFILES_DIR/modules/sunshine/sunshine-scripts/sunhsine-detached-dual.sh"
            ],
            "elevated": false,
            "exclude-global-prep-cmd": false,
            "exit-timeout": 5,
            "image-path": "",
            "name": "Dual",
            "output": "",
            "prep-cmd": [
                {
                    "do": "$DOTFILES_DIR/modules/sunshine/sunshine-scripts/sunhsine-start-single.sh",
                    "undo": "$DOTFILES_DIR/modules/sunshine/sunshine-scripts/sunhsine-end.sh"
                }
            ],
            "wait-all": true
        },
        {
            "auto-detach": true,
            "exclude-global-prep-cmd": false,
            "exit-timeout": 5,
            "image-path": "",
            "name": "Single",
            "prep-cmd": [
                {
                    "do": "$DOTFILES_DIR/modules/sunshine/sunshine-scripts/sunhsine-start-single.sh",
                    "undo": "$DOTFILES_DIR/modules/sunshine/sunshine-scripts/sunhsine-end.sh"
                }
            ],
            "wait-all": true
        }
    ],
    "env": {
        "PATH": "\$(PATH):\$(HOME)/.local/bin"
    }
}
EOF
)" ~/.config/sunshine/apps.json

