#!/usr/bin/env sh
set -e


cmd sudo rm -rf /root/.config/nvim || true
cmd sudo install -D -m 755 ./init.lua /root/.config/nvim/init.lua

cmd rm -rf ~/.config/nvim || true
cmd install -D -m 755 ./init.lua ~/.config/nvim/init.lua

cmd sudo install -D -m 755 "$(writetext <<'EOF'
export EDITOR="nvim"
EOF
)" /etc/profile.d/dotfiles-neovim.sh

