#!/usr/bin/env sh
set -e

usage() {
	cat <<EOF
Example: config $DOTFILES_MODULE_NAME
EOF
}
usage_err() {
	if ! [ "$1" = "" ]; then
		echo "$1" >&2
	fi
	usage
	exit 1
}

while [ $# -gt 0 ]; do
	case $1 in
		*)
			usage_err "Invalid option: $1"
			;;
	esac
	shift
done

set +e
cmd sudo rm -f /etc/xdg/autostart/com.cloudflare.WarpTaskbar.desktop
set -e
cmd sudo install -D -m 644 ./10-warp-svc.rules /etc/polkit-1/rules.d/10-warp-svc.rules
cmd sudo install -D -m 755 ./warp /usr/local/bin/warp


