#!/bin/bash

width=2240
height=1400

wlr-randr --output 'eDP-1' --mode "${width}x${height}" --pos '0,0' --transform 'normal' --scale '1.5' --preferred
echo 180 > /sys/class/backlight/amdgpu_bl0/brightness

riverctl keyboard-layout -options "grp:caps_toggle" 'us(dvorak),ru'
riverctl set-repeat 50 300
riverctl input pointer-1739-52781-MSFT0003:00_06CB:CE2D_Touchpad tap enabled

# riverctl rule-add -app-id 'float*' -title 'foo' float
riverctl rule-add -app-id "zen" ssd
riverctl rule-add -app-id "zen" tags 2
riverctl rule-add -app-id "zen" fullscreen
riverctl default-layout rivertile
riverctl focus-follows-cursor normal
riverctl background-color 0x1e1e2e
riverctl border-width 1
riverctl border-color-focused 0xf5e0dc
riverctl border-color-unfocused 0x1e1e2e

riverctl map normal Super+Shift Return spawn "KITTY_ENABLE_WAYLAND=1 kitty"
riverctl map normal Super P spawn "BEMENU_BACKEND=wayland BEMENU_OPTS='--fb \"#1e1e2e\" --ff \"#cdd6f4\" --nb \"#1e1e2e\" --nf \"#cdd6f4\" --tb \"#1e1e2e\" --hb \"#1e1e2e\" --tf \"#f38ba8\" --hf \"#f9e2af\" --af \"#cdd6f4\" --ab \"#1e1e2e\" -H 20 -i' bemenu-run"
riverctl map normal Super+Shift C close
riverctl map normal Control+Alt Backspace exit
riverctl map normal Super+Shift F toggle-fullscreen
riverctl map -repeat normal Super F5 spawn 'echo $(($(cat /sys/class/backlight/amdgpu_bl0/brightness)-15)) > /sys/class/backlight/amdgpu_bl0/brightness'
riverctl map -repeat normal Super F6 spawn 'echo $(($(cat /sys/class/backlight/amdgpu_bl0/brightness)+15)) > /sys/class/backlight/amdgpu_bl0/brightness'
riverctl map -repeat normal Super F6 spawn 'echo $(($(cat /sys/class/backlight/amdgpu_bl0/brightness)+15)) > /sys/class/backlight/amdgpu_bl0/brightness'
riverctl map -repeat normal Super Down spawn "new_volume=\$((\$(echo \"\$(pactl get-sink-volume @DEFAULT_SINK@)\" | head -1 | sed 's/%.*//; s/.*\/ //') + -5)); [ \${new_volume} -le 150 ] && pactl set-sink-volume @DEFAULT_SINK@ \"\${new_volume}%\" || exit 1"
riverctl map -repeat normal Super Up spawn "new_volume=\$((\$(echo \"\$(pactl get-sink-volume @DEFAULT_SINK@)\" | head -1 | sed 's/%.*//; s/.*\/ //') + +5)); [ \${new_volume} -le 150 ] && pactl set-sink-volume @DEFAULT_SINK@ \"\${new_volume}%\" || exit 1"
riverctl map -repeat normal Super Left spawn "pactl set-sink-mute @DEFAULT_SINK@ toggle"
riverctl map -repeat normal Super Right spawn "[ \"\$(pactl list cards | grep 'HiFi' | awk -F': ' '/Active Profile/ { print \$2 }')\" = 'HiFi (Mic1, Mic2, Speaker)' ] && pactl set-card-profile 49 'HiFi (Headphones, Mic1, Mic2)' || pactl set-card-profile 49 'HiFi (Mic1, Mic2, Speaker)'"

# layout stack
riverctl map normal Super V toggle-float
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous
riverctl map normal Super Return zoom
riverctl map -repeat normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map -repeat normal Super L send-layout-cmd rivertile "main-ratio +0.05"
# riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
# riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"
# riverctl map normal Super Up send-layout-cmd rivertile "main-location top"
# riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
# riverctl map normal Super Down send-layout-cmd rivertile "main-location bottom"
# riverctl map normal Super Left send-layout-cmd rivertile "main-location left"
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags
done

printenv > ${SESSION_ENV}

/usr/libexec/xdg-desktop-portal-wlr &
yambar &
rivertile -view-padding 0 -outer-padding 0 &
