#!/usr/bin/env sh
set -e

usage() {
	cat <<EOF
Example: config $DOTFILES_MODULE_NAME --nopasswd
EOF
}
usage_err() {
	if ! [ "$1" = "" ]; then
		echo "$1" >&2
	fi
	usage
	exit 1
}

while [ $# -gt 0 ]; do
	case $1 in
		--autologin)
			autologin=true
			;;
		--nopasswd)
			nopasswd=true
			;;
		*)
			usage_err "Invalid option: $1"
			;;
	esac
	shift
done

cmd sudo install -D -m 644 "$(writetext <<EOF
$([ $autologin ] && cat <<EOF2
[Autologin]
User=$(whoami)
Session=plasma
EOF2
)

[Wayland]
EnableHiDPI=true
CompositorCommand=kwin_wayland --drm --no-lockscreen --no-global-shortcuts --locale1

[X11]
EnableHiDPI=true

[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell
EOF
)" /etc/sddm.conf.d/dotfiles.conf

cmd sudo install -D -m 644 "$(writetext <<EOF
#%PAM-1.0

$([ $nopasswd ] && cat <<EOF2
auth      sufficient    pam_succeed_if.so user = $(whoami)
EOF2
)
auth        include     system-login
-auth       optional    pam_gnome_keyring.so
-auth       optional    pam_kwallet5.so

account     include     system-login

password    include     system-login
-password   optional    pam_gnome_keyring.so    use_authtok

session     optional    pam_keyinit.so          force revoke
session     include     system-login
-session    optional    pam_gnome_keyring.so    auto_start
-session    optional    pam_kwallet5.so         auto_start
EOF
)" /etc/pam.d/sddm

cmd sudo systemctl enable sddm.service
