#!/usr/bin/env -S sh -e

cmd install -Dm644 ./crackling-fix.conf ~/.config/pipewire/pipewire.conf.d/crackling-fix.conf
# cmd install -Dm644 ./crackling-fix-pulse.conf ~/.config/pipewire/pipewire-pulse.conf.d/crackling-fix.conf
