#!/usr/bin/env -S sh -e

cmd install -Dm644 "$(writetext <<EOF
context.properties = {
	default.clock.min-quantum = 4096
}
EOF
)" ~/.config/pipewire/pipewire.conf.d/crackling-fix.conf
cmd install -Dm644 "$(writetext <<EOF
pulse.properties = {
	pulse.min.req = 4096/48000
	pulse.min.frag = 4096/48000
	pulse.min.quantum = 4096/48000
}
EOF
)" ~/.config/pipewire/pipewire-pulse.conf.d/crackling-fix.conf
cmd install -Dm644 "$(writetext <<EOF
monitor.alsa.rules = [
  {
    matches = [
      {
        # Matches all sources
        node.name = "~alsa_input.*"
      },
      {
        # Matches all sinks
        node.name = "~alsa_output.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
# bluetooth devices
monitor.bluez.rules = [
  {
    matches = [
      {
        # Matches all sources
        node.name = "~bluez_input.*"
      },
      {
        # Matches all sinks
        node.name = "~bluez_output.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
EOF
)" ~/.config/wireplumber/wireplumber.conf.d/disable-suspension.conf
