title Arch Linux - Bazzite kernel
linux /vmlinuz-linux-bazzite
initrd /initramfs-linux-bazzite.img
options root=LABEL=arch-root rw nowatchdog fbcon=vc:2-6 amdgpu.sg_display=0 drm.edid_firmware=DP-3:edid/v226hql.bin
