SOURCE_DIR="/"
DEST_DIR="${MY_DOTFILES_DIR}/root-${MY_DOTFILES_DEVICE}/"
CONF_FILES="/etc/hostname
/etc/fstab
/etc/modules-load.d
/etc/sysctl.d
/etc/tlp.conf
/etc/locale.conf
/etc/pacman.conf
/etc/paru.conf
/etc/nftables.conf
/etc/vconsole.conf
/etc/ebmm.conf
/etc/mkinitcpio.conf
/etc/mkinitcpio.d
/etc/mkinitcpio.conf.d
/etc/udev/rules.d
/etc/systemd/system/nethandler.service
/etc/systemd/user/ssh-agent.service
/etc/systemd/resolved.conf
/etc/systemd/network
/etc/libvirt/hooks
/etc/X11/xorg.conf.d
/etc/X11/xorg.conf
/etc/default/scx"
PACKAGES_FILE="${MY_DOTFILES_DIR}/packages-${MY_DOTFILES_DEVICE}"
