#!/usr/bin/env sh
set -e

cmd sudo ln -sf /usr/share/zoneinfo/Asia/Tomsk /etc/localtime
cmd sudo install -D -m 644 "$(writetext <<EOF
LANG=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_TIME=en_US.UTF-8
EOF
)" /etc/locale.conf
cmd sudo install -D -m 644 "$(writetext "KEYMAP=dvorak")" /etc/vconsole.conf
cmd sudo install -D -m 644 "$(writetext "cachyos")" /etc/hostname
cmd sudo install -D -m 644 "$(writetext <<EOF
en_CA.UTF-8 UTF-8
en_CA ISO-8859-1
en_US.UTF-8 UTF-8
en_US ISO-8859-1
ru_RU.KOI8-R KOI8-R
ru_RU.UTF-8 UTF-8
ru_RU ISO-8859-5
EOF
)" /etc/locale.gen

add_module_temp "env-LATE" "$(writetext <<'EOF'
export XDG_CACHE_HOME="$HOME/.cache";
export XDG_CONFIG_HOME="$HOME/.config";
export XDG_DATA_HOME="$HOME/.local/share";
export XDG_STATE_HOME="$HOME/.local/state";
export PATH="$PATH:$HOME/.local/bin"
export HISTFILE="$XDG_STATE_HOME/bash/history";
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv";
export CARGO_HOME="$XDG_DATA_HOME/cargo";
export GOPATH="$XDG_DATA_HOME/go";
export NPM_CONFIG_INIT_MODULE="$XDG_CONFIG_HOME/npm/config/npm-init.js";
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm";
export NPM_CONFIG_TMP="$XDG_RUNTIME_DIR/npm";
EOF
)"

cmd sudo usermod -aG wheel,audio,video,input,tty,kvm,network "$(whoami)"

add_module_temp "hosts-LATE" "$(writetext <<'EOF'
127.0.0.1        localhost
::1              localhost
EOF
)"

add_module_temp "sysctl-LATE" "$(writetext <<'EOF'
EOF
)"

