#!/usr/bin/env sh
set -e

cmd sudo install -D -m 644 ./pacman.conf /etc/pacman.conf

cmd sudo ln -sf /usr/share/zoneinfo/Asia/Tomsk /etc/localtime
cmd sudo install -D -m 644 "$(writetext "LANG=en_US.UTF-8")" /etc/locale.conf
cmd sudo install -D -m 644 "$(writetext "KEYMAP=dvorak")" /etc/vconsole.conf
cmd sudo install -D -m 644 "$(writetext "arch")" /etc/hostname
cmd sudo install -D -m 644 "$(writetext <<EOF
en_CA.UTF-8 UTF-8
en_CA ISO-8859-1
en_US.UTF-8 UTF-8
en_US ISO-8859-1
ru_RU.KOI8-R KOI8-R
ru_RU.UTF-8 UTF-8
ru_RU ISO-8859-5
EOF
)" /etc/locale.gen

cmd sudo install -D -m 755 "$(writetext <<'EOF'
export XDG_CACHE_HOME="$HOME/.cache";
export XDG_CONFIG_HOME="$HOME/.config";
export XDG_DATA_HOME="$HOME/.local/share";
export XDG_STATE_HOME="$HOME/.local/state";
export PATH="$PATH:$HOME/.local/bin"
export HISTFILE="$XDG_STATE_HOME/bash/history";
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv";
export CARGO_HOME="$XDG_DATA_HOME/cargo";
export GOPATH="$XDG_DATA_HOME/go";
export NPM_CONFIG_INIT_MODULE="$XDG_CONFIG_HOME/npm/config/npm-init.js";
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm";
export NPM_CONFIG_TMP="$XDG_RUNTIME_DIR/npm";
EOF
)" /etc/profile.d/dotfiles-base.sh

cmd sudo usermod -aG wheel,audio,video,input,tty,kvm,network "$(whoami)"

cmd sudo timedatectl set-ntp true

add_module_temp "hosts-LATE" "$(writetext <<'EOF'
127.0.0.1        localhost
::1              localhost
EOF
)"

cmd sudo install -D -m 644 "$(writetext <<'EOF'
# The sysctl swappiness parameter determines the kernel's preference for pushing anonymous pages or page cache to disk in memory-starved situations.
# A low value causes the kernel to prefer freeing up open files (page cache), a high value causes the kernel to try to use swap space,
# and a value of 100 means IO cost is assumed to be equal.
vm.swappiness = 100

# The value controls the tendency of the kernel to reclaim the memory which is used for caching of directory and inode objects (VFS cache).
# Lowering it from the default value of 100 makes the kernel less inclined to reclaim VFS cache (do not set it to 0, this may produce out-of-memory conditions)
vm.vfs_cache_pressure = 50

# Contains, as bytes, the number of pages at which a process which is
# generating disk writes will itself start writing out dirty data.
vm.dirty_bytes = 268435456

# page-cluster controls the number of pages up to which consecutive pages are read in from swap in a single attempt.
# This is the swap counterpart to page cache readahead. The mentioned consecutivity is not in terms of virtual/physical addresses,
# but consecutive on swap space - that means they were swapped out together. (Default is 3)
# increase this value to 1 or 2 if you are using physical swap (1 if ssd, 2 if hdd)
vm.page-cluster = 0

# Contains, as bytes, the number of pages at which the background kernel
# flusher threads will start writing out dirty data.
vm.dirty_background_bytes = 67108864

# The kernel flusher threads will periodically wake up and write old data out to disk.  This
# tunable expresses the interval between those wakeups, in 100'ths of a second (Default is 500).
vm.dirty_writeback_centisecs = 1500

# This action will speed up your boot and shutdown, because one less module is loaded. Additionally disabling watchdog timers increases performance and lowers power consumption
# Disable NMI watchdog
kernel.nmi_watchdog = 0

# Enable the sysctl setting kernel.unprivileged_userns_clone to allow normal users to run unprivileged containers.
kernel.unprivileged_userns_clone = 1

# To hide any kernel messages from the console
kernel.printk = 3 3 3 3

# Restricting access to kernel pointers in the proc filesystem
kernel.kptr_restrict = 2

# Increase netdev receive queue
# May help prevent losing packets
net.core.netdev_max_backlog = 4096

# Set size of file handles and inode cache
fs.file-max = 2097152
EOF
)" /etc/sysctl.d/99-dotfiles-base.conf

cmd sudo install -D -m 644 "$(writetext <<'EOF'
blacklist pcscpkr
blacklist iTCO_wdt
blacklist sp5100_tco
EOF
)" /etc/modprobe.d/dotfiles-base.conf

cmd sudo install -D -m 644 "$(writetext <<'EOF'
# Improve performance for applications that use tcmalloc
# https://github.com/google/tcmalloc/blob/master/docs/tuning.md#system-level-optimizations
w! /sys/kernel/mm/transparent_hugepage/defrag - - - - defer+madvise
EOF
)" /etc/tmpfiles.d/dotfiles-thp.conf

cmd sudo install -D -m 644 "$(writetext <<'EOF'
# THP Shrinker has been added in the 6.12 Kernel
# Default Value is 511
# THP=always policy vastly overprovisions THPs in sparsely accessed memory areas, resulting in excessive memory pressure and premature OOM killing
# 409 means that any THP that has more than 409 out of 512 (80%) zero filled filled pages will be split.
# This reduces the memory usage, when THP=always used and the memory usage goes down to around the same usage as when madvise is used, while still providing an equal performance improvement
w! /sys/kernel/mm/transparent_hugepage/khugepaged/max_ptes_none - - - - 409
EOF
)" /etc/tmpfiles.d/dotfiles-thp-shrinker.conf

cmd sudo install -D -m 644 "$(writetext <<'EOF'
# Override coredump cleanup age from 2w (systemd default) to 3d
e /var/lib/systemd/coredump - - - 3d
EOF
)" /etc/tmpfiles.d/dotfiles-coredump.conf

cmd sudo install -D -m 644 "$(writetext <<'EOF'
ntsync
EOF
)" /etc/modules-load.d/dotfiles-ntsync.conf

cmd sudo systemctl enable systemd-oomd.service

