[
	{
		"name": "linux",
		"params": "root=LABEL=root rootfstype=ext4 rw nowatchdog module_blacklist=pcspkr",
		"initrd": "\\initramfs-linux.img",
		"loader": "\\vmlinuz-linux",
		"partition_label": "boot"
	}
]
