#!/usr/bin/env sh

dualsense_name="alsa_output.usb-Sony_Interactive_Entertainment_DualSense_Wireless_Controller-00.analog-surround-40"
if [ "$1" == "toggle" ]; then
	if [ "$(pw-link -l | xargs | grep "playback.surround_40_output:output_FL |-> $dualsense_name:playback_FL |-> $dualsense_name:playback_RL")" == "" ]; then
		echo "activating"
		pw-link playback.surround_40_output:output_FL $dualsense_name:playback_RL
		pw-link playback.surround_40_output:output_FR $dualsense_name:playback_RR
	else
		echo "deactivating"
		pw-link -d playback.surround_40_output:output_FL $dualsense_name:playback_RL
		pw-link -d playback.surround_40_output:output_FR $dualsense_name:playback_RR
	fi
elif [ "$1" == "level" ]; then
	if [ "$2" == "" ]; then
		echo "provide a level (number in range 0 to 100)"
		exit 1
	fi
	level="$2"
	pactl set-sink-volume $dualsense_name 100% 100% $level% $level%
else
	echo "no such command"
	exit 1
fi

