#!/usr/bin/env -S sh -e

cmd install -D -m 644 ./dualsense-stereo.conf ~/.config/pipewire/pipewire.conf.d/dualsense-stereo.conf
cmd sudo install -D -m 755 ./dualsound /usr/local/bin/dualsound
cmd sudo install -D -m 644 ./72-dualsense.rules /etc/udev/rules.d/72-dualsense.rules

