#!/usr/bin/env sh

if [ "$1" = "default" ]; then
	if ([ ! "$KDE_SESSION_UID" == "" ] || [ "$XDG_CURRENT_DESKTOP" == "KDE" ]) && ([ ! "$WAYLAND_DISPLAY" == "" ] || [ "$XDG_SESSION_TYPE" == "wayland" ]); then
		kwriteconfig6 --file ~/.config/kxkbrc --group Layout --key LayoutList "us,ru"
		kwriteconfig6 --file ~/.config/kxkbrc --group Layout --key VariantList "dvorak,"
		kwriteconfig6 --file ~/.config/kxkbrc --group Layout --key Options "terminate:ctrl_alt_bksp,grp:caps_toggle"
		kwriteconfig6 --file ~/.config/kxkbrc --group Layout --key ResetOldOptions "true"
		kwriteconfig6 --file ~/.config/kxkbrc --group Layout --key Use "true"
		# # this was removed for some reason
		# dbus-send --session --type=signal --dest=org.kde.keyboard /Layouts org.kde.keyboard.reloadConfig
		# TODO: Maybe find a way to apply keyboard settings automatically
		exec systemsettings kcm_keyboard
	else
		setxkbmap -layout us,ru -variant dvorak, -option "grp:caps_toggle" -option "terminate:ctrl_alt_bksp"
	fi
elif [ "$1" = "gaming" ]; then
	if ([ ! "$KDE_SESSION_UID" == "" ] || [ "$XDG_CURRENT_DESKTOP" == "KDE" ]) && ([ ! "$WAYLAND_DISPLAY" == "" ] || [ "$XDG_SESSION_TYPE" == "wayland" ]); then
		kwriteconfig6 --file ~/.config/kxkbrc --group Layout --key LayoutList "us,ru"
		kwriteconfig6 --file ~/.config/kxkbrc --group Layout --key VariantList ","
		kwriteconfig6 --file ~/.config/kxkbrc --group Layout --key Options "terminate:ctrl_alt_bksp,grp:caps_toggle"
		kwriteconfig6 --file ~/.config/kxkbrc --group Layout --key ResetOldOptions "true"
		kwriteconfig6 --file ~/.config/kxkbrc --group Layout --key Use "true"
		# # this was removed for some reason
		# dbus-send --session --type=signal --dest=org.kde.keyboard /Layouts org.kde.keyboard.reloadConfig
		# TODO: Maybe find a way to apply keyboard settings automatically
		exec systemsettings kcm_keyboard
	else
		setxkbmap -layout us -option "terminate:ctrl_alt_bksp"
	fi
else
	echo "Unknown option: [$1]" >&2
	exit 1
fi

