#!/usr/bin/env -S sh -e

cmd sudo install -D -m 644 ./ssh-agent.service /etc/systemd/user/ssh-agent.service
cmd sudo systemctl daemon-reload
cmd systemctl --user enable ssh-agent.service

cmd sudo install -D -m 755 "$(writetext <<'EOF'
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.sock"
EOF
)" /etc/profile.d/ssh-agent.sh
