#!/usr/bin/env sh
set -e

cmd sudo install -D -m 644 ./ssh-agent.service /etc/systemd/user/ssh-agent.service
cmd sudo systemctl daemon-reload
cmd systemctl --user enable ssh-agent.service

add_module_temp "env-LATE" "$(writetext "export SSH_AUTH_SOCK=\"\$XDG_RUNTIME_DIR/ssh-agent.sock\"")"

set +e
cmd rm -rf ~/.ssh
cmd mkdir ~/.ssh
cmd chmod 700 ~/.ssh
set -e

for file in $DOTFILES_MODULE_SECRETS/.ssh/*; do
	[ -f "$file" ] || continue
	base=$(basename "$file")
	cmd cp "$file" ~/.ssh/
	if [[ "$base" == *.pub ]]; then chmod 644 ~/.ssh/"$base"
	elif [[ "$base" == known_hosts ]]; then chmod 644 ~/.ssh/"$base"
	else chmod 600 ~/.ssh/"$base"; fi
done
