# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe -fomit-frame-pointer"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"
MAKEOPTS="-j12 -l12"

USE="minimal wayland pipewire vulkan opengl qt6 multilib lto pgojit xs orc threads asm openmp X a52 aac acpi alsa cairo dri dts encode exif flac gif gtk icu jpeg kf6compat lcms mad mng mp3 mp4 mpeg oog pango pdf png ppds qml qt5 sdl sound svg tiff truetype vorbis udev unicode upower usb xcb xft x264 xml xv xvid dbus egl harfbuzz pulseaudio -elogind -polkit -systemd -logind"
ACCEPT_LICENSE="*"
# FEATURES="${FEATURES} getbinpkg"

EMERGE_DEFAULT_OPTS="--ask --verbose --with-bdeps=y --complete-graph=y --getbinpkg=y --binpkg-respect-use=y"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.utf8
# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

