#!/usr/bin/env sh
set -e

usage() {
	cat <<EOF
Example: config $DOTFILES_MODULE_NAME --modules "
pcscpkr
iTCO_wdt
sp5100_tco
"
EOF
}
usage_err() {
	if ! [ "$1" = "" ]; then
		echo "$1" >&2
	fi
	usage
	exit 1
}

while [ $# -gt 0 ]; do
	case $1 in
		--modules)
			if ! [ "$2" = "" ]; then
				modules="$(rm_empty "$2" | sed 's|^|blacklist |')"
				shift
			fi
			;;
		*)
			usage_err "Invalid option: $1"
			;;
	esac
	shift
done

file="$(writetext "$modules")"
cmd sudo install -D -m 644 "$file" /etc/modprobe.d/dotfiles.conf
