#!/usr/bin/env sh
set -e

cmd sudo install -D -m 644 "$(writetext <<'EOF'
FILES=(/usr/lib/firmware/edid/v226hql.bin)
EOF
)" /etc/mkinitcpio.conf.d/v226hql.conf

cmd sudo install -D -m 644 ./v226hql.bin /usr/lib/firmware/edid/v226hql.bin

add_module_temp "plasma-LATE" "$(writetext <<'EOF'
            MenuItem {
                text: "1920x1080@70"
                icon.name: "system-run"
                onTriggered: {
                    executable.exec(`bash -c 'kscreen-doctor output.HDMI-A-1.mode.1920x1080@70'`)
                }
            }
            MenuItem {
                text: "1600x900@75"
                icon.name: "system-run"
                onTriggered: {
                    executable.exec(`bash -c 'kscreen-doctor output.HDMI-A-1.mode.1600x900@75'`)
                }
            }
            MenuItem {
                text: "1920x1080@60"
                icon.name: "system-run"
                onTriggered: {
                    executable.exec(`bash -c 'kscreen-doctor output.HDMI-A-1.mode.1920x1080@60'`)
                }
            }
EOF
)"
