#!/usr/bin/env sh
set -e

cmd sudo install -D -m 644 "$(writetext <<'EOF'
FILES=(/usr/lib/firmware/edid/v226hql.bin)
EOF
)" /etc/mkinitcpio.conf.d/v226hql.conf

cmd sudo install -D -m 644 ./v226hql.bin /usr/lib/firmware/edid/v226hql.bin
