[[boots]]
name = 'linux'
initrd = '\initramfs-linux.img'
loader = '\vmlinuz-linux'
params = 'root=LABEL=root rw nowatchdog intel_iommu=on module_blacklist=iTCO_wdt,nouveau,i915 nvidia_drm.modeset=1 nvidia_drm.fbdev=1 nouveau.modeset=0 i915.modeset=0 nvidia.NVreg_UsePageAttributeTable=1 nvidia.NVreg_EnablePCIeGen3=1 nvidia.NVreg_DynamicPowerManagement=0'
partition_label = 'boot'

[[boots]]
name = 'linux-bazzite'
initrd = '\initramfs-linux-bazzite.img'
loader = '\vmlinuz-linux-bazzite'
params = 'root=LABEL=root rw nowatchdog intel_iommu=on module_blacklist=iTCO_wdt,nouveau,i915 nvidia_drm.modeset=1 nvidia_drm.fbdev=1 nouveau.modeset=0 i915.modeset=0 nvidia.NVreg_UsePageAttributeTable=1 nvidia.NVreg_EnablePCIeGen3=1 nvidia.NVreg_DynamicPowerManagement=0 quiet loglevel=3 rd.udev.log_level=3'
partition_label = 'boot'
