EBMM_KERNEL="linux"
EBMM_IMG=""
EBMM_OPTS="root=LABEL=root rw nowatchdog intel_iommu=on module_blacklist=iTCO_wdt,nouveau,i915 nvidia_drm.modeset=1 nvidia_drm.fbdev=1 nouveau.modeset=0 i915.modeset=0 nvidia.NVreg_UsePageAttributeTable=1 nvidia.NVreg_EnablePCIeGen3=1 nvidia.NVreg_DynamicPowerManagement=0"
EBMM_BOOT_PARTITION_LABEL="boot"
