#!/usr/bin/env sh
set -e

usage() {
	cat <<EOF
Example: config $DOTFILES_MODULE_NAME
EOF
}
usage_err() {
	[ "$1" ] && echo "$1" >&2
	usage
	exit 1
}

while [ $# -gt 0 ]; do
	case $1 in
		--search-engine | -se )
			search_engine=1
			;;
		*)
			usage_err "Invalid option: $1"
			;;
	esac
	shift
done

cmd sudo install -D -m 644 "$(writetext <<EOF
{
  "policies": {
    "ExtensionSettings": {
      "uBlock0@raymondhill.net": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi",
        "installation_mode": "force_installed"
      },
      "addon@darkreader.org": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/darkreader/latest.xpi",
        "installation_mode": "force_installed"
      },
      "{762f9885-5a13-4abd-9c77-433dcd38b8fd}": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/return-youtube-dislikes/latest.xpi",
        "installation_mode": "force_installed"
      },
      "sponsorBlocker@ajay.app": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/sponsorblock/latest.xpi",
        "installation_mode": "force_installed"
      },
      "{74145f27-f039-47ce-a470-a662b129930a}": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/clearurls/latest.xpi",
        "installation_mode": "force_installed"
      }
    },
$([ "$search_engine" = "1" ] && cat << 'SEARCH'
    "SearchEngines": {
      "Add": [
        {
          "Name": "SearchEngine",
          "URLTemplate": "http://localhost:4444/search?q={searchTerms}",
          "Method": "GET",
          "Alias": "@searchengine",
          "SuggestURLTemplate": "http://localhost:4444/api/suggest/opensearch?q={searchTerms}"
        }
      ],
      "Default": "SearchEngine"
    },
SEARCH
)
    "Preferences": {
      "browser.search.suggest.enabled": {
        "Value": true,
        "Status": "locked"
      },
      "browser.translations.neverTranslateLanguages": {
        "Value": "ru",
        "Status": "default"
      },
      "media.videocontrols.picture-in-picture.video-toggle.enabled": {
        "Value": false,
        "Status": "locked"
      },
      "sidebar.visibility": {
        "Value": "hide-sidebar",
        "Status": "locked"
      },
      "signon.rememberSignons": {
        "Value": false,
        "Status": "locked"
      },
      "browser.tabs.insertAfterCurrent": {
        "Value": true,
        "Status": "locked"
      }
    }
  }
}
EOF
)" /etc/zen/policies/policies.json

