#!/usr/bin/env sh
set -e

# cmd sudo install -D -m 644 "$(writetext <<'EOF'
# FILES=(/usr/lib/firmware/edid/legiongo.bin)
# EOF
# )" /etc/mkinitcpio.conf.d/legiongo.conf
#
# cmd sudo install -D -m 644 ./legiongo.bin /usr/lib/firmware/edid/legiongo.bin
