#!/usr/bin/env sh
set -e

usage() {
	cat <<EOF
Example: config $DOTFILES_MODULE_NAME
EOF
}
usage_err() {
	if ! [ "$1" = "" ]; then
		echo "$1" >&2
	fi
	usage
	exit 1
}

while [ $# -gt 0 ]; do
	case $1 in
		*)
			usage_err "Invalid option: $1"
			;;
	esac
	shift
done

cmd sudo systemctl enable libvirtd
set +e
cmd sudo virsh net-start default
cmd sudo virsh net-autostart default
set -e
cmd sudo usermod -aG kvm,input,libvirt "$(whoami)"

cmd sudo install -D -m 755 "$(writetext <<'EOF'
export LIBVIRT_DEFAULT_URI="qemu:///system"
EOF
)" /etc/profile.d/virt.sh

cmd sudo install -D -m 755 "$(writetext <<'EOF'
#!/bin/bash

GUEST_NAME="$1"
HOOK_NAME="$2"
STATE_NAME="$3"
MISC="${@:4}"

BASEDIR="$(dirname $0)"

HOOKPATH="$BASEDIR/qemu.d/$GUEST_NAME/$HOOK_NAME/$STATE_NAME"
set -e # If a script exits with an error, we should as well.

if [ -f "$HOOKPATH" ]; then
eval \""$HOOKPATH"\" "$@"
elif [ -d "$HOOKPATH" ]; then
while read file; do
  eval \""$file"\" "$@"
done <<< "$(find -L "$HOOKPATH" -maxdepth 1 -type f -executable -print;)"
fi
EOF
)" /etc/libvirt/hooks/qemu

cmd sudo install -D -m 755 "$(writetext <<EOF
#!/bin/bash
set -x

systemctl stop display-manager
systemctl --user -M $(whoami)@ stop plasma*

modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia

systemctl set-property --runtime -- system.slice AllowedCPUs=0,6
systemctl set-property --runtime -- user.slice AllowedCPUs=0,6
systemctl set-property --runtime -- init.scope AllowedCPUs=0,6
command -v powerprofilectl >/dev/null 2>&1 && powerprofilectl set performance || true
EOF
)" /etc/libvirt/hooks/qemu.d/win-passthrough/prepare/begin/start.sh

cmd sudo install -D -m 755 "$(writetext <<'EOF'
#!/bin/bash
set -x

systemctl set-property --runtime -- system.slice AllowedCPUs=0-11
systemctl set-property --runtime -- user.slice AllowedCPUs=0-11
systemctl set-property --runtime -- init.scope AllowedCPUs=0-11
command -v powerprofilectl >/dev/null 2>&1 && powerprofilectl set balanced || true

modprobe nvidia_drm
modprobe nvidia_modeset
modprobe nvidia_uvm
modprobe nvidia

systemctl start display-manager
EOF
)" /etc/libvirt/hooks/qemu.d/win-passthrough/release/end/stop.sh

cmd sudo install -D -m 755 ./virt /usr/local/bin/virt
