#!/usr/bin/env sh
set -e

usage() {
	cat <<EOF
Example: config $DOTFILES_MODULE_NAME
EOF
}
usage_err() {
	if ! [ "$1" = "" ]; then
		echo "$1" >&2
	fi
	usage
	exit 1
}

while [ $# -gt 0 ]; do
	case $1 in
		--sunshine)
			[ "$2" = "" ] && usage_err "Argument not specified"
			sunshine="$2"
			shift
			;;
		*)
			usage_err "Invalid option: $1"
			;;
	esac
	shift
done

cmd sudo systemctl enable libvirtd
set +e
cmd sudo virsh net-start default
cmd sudo virsh net-autostart default
set -e
cmd sudo usermod -aG kvm,input,libvirt "$(whoami)"

add_module_temp "env-LATE" "$(writetext "export LIBVIRT_DEFAULT_URI=\"qemu:///system\"")"

cmd sudo install -D -m 755 "$(writetext <<'EOF'
#!/bin/bash

GUEST_NAME="$1"
HOOK_NAME="$2"
STATE_NAME="$3"
MISC="${@:4}"

BASEDIR="$(dirname $0)"

HOOKPATH="$BASEDIR/qemu.d/$GUEST_NAME/$HOOK_NAME/$STATE_NAME"
set -e # If a script exits with an error, we should as well.

if [ -f "$HOOKPATH" ]; then
eval \""$HOOKPATH"\" "$@"
elif [ -d "$HOOKPATH" ]; then
while read file; do
  eval \""$file"\" "$@"
done <<< "$(find -L "$HOOKPATH" -maxdepth 1 -type f -executable -print;)"
fi
EOF
)" /etc/libvirt/hooks/qemu

cmd sudo install -D -m 755 "$(writetext <<EOF
#!/bin/bash
set -x

systemctl stop display-manager
systemctl --user -M $(whoami)@ stop plasma*

modprobe -r nvidia_drm nvidia_modeset nvidia_uvm nvidia snd_hda_intel

virsh nodedev-detach pci_0000_05_00_0
virsh nodedev-detach pci_0000_05_00_1
virsh nodedev-detach pci_0000_07_00_4

modprobe vfio-pci

systemctl set-property --runtime -- system.slice AllowedCPUs=0,6
systemctl set-property --runtime -- user.slice AllowedCPUs=0,6
systemctl set-property --runtime -- init.scope AllowedCPUs=0,6
command -v powerprofilectl >/dev/null 2>&1 && powerprofilectl set performance || true
EOF
)" /etc/libvirt/hooks/qemu.d/win-passthrough/prepare/begin/start.sh

cmd sudo install -D -m 755 "$(writetext <<'EOF'
#!/bin/bash
set -x

systemctl set-property --runtime -- system.slice AllowedCPUs=0-11
systemctl set-property --runtime -- user.slice AllowedCPUs=0-11
systemctl set-property --runtime -- init.scope AllowedCPUs=0-11
command -v powerprofilectl >/dev/null 2>&1 && powerprofilectl set balanced || true

modprobe -r vfio-pci

virsh nodedev-reattach pci_0000_05_00_0
virsh nodedev-reattach pci_0000_05_00_1
virsh nodedev-reattach pci_0000_07_00_4

modprobe nvidia_drm
modprobe nvidia_modeset
modprobe nvidia_uvm
modprobe nvidia
modprobe snd_hda_intel

systemctl start display-manager
EOF
)" /etc/libvirt/hooks/qemu.d/win-passthrough/release/end/stop.sh

if ! [ "$sunshine" = "" ]; then
	cmd sudo install -D -m 755 "$(writetext <<EOF
#!/bin/bash

VM_NAME="\$1"
nohup bash -c '
	nft -f /etc/nftables.conf

	VM_NAME="'"\$VM_NAME"'"
	VM_IP=""
	for i in \$(seq 1 30); do
		VM_IP="\$(virsh domifaddr "\$VM_NAME" | grep -oP "(\\d+\\.){3}\\d+" | head -1)"
		[ -n "\$VM_IP" ] && break
		sleep 2
	done

	nft add rule ip filter FORWARD ip daddr \$VM_IP tcp dport { 47984-47990, 48010 } accept
	nft add rule ip filter FORWARD ip daddr \$VM_IP udp dport { 47998-48000 } accept

	nft add table ip nat

	nft add chain ip nat prerouting { type nat hook prerouting priority dstnat \\; policy accept \\; }
	nft add rule ip nat prerouting iifname "$sunshine" tcp dport 47984-47990 dnat to \$VM_IP:47984-47990
	nft add rule ip nat prerouting iifname "$sunshine" tcp dport 48010 dnat to \$VM_IP:48010
	nft add rule ip nat prerouting iifname "$sunshine" udp dport 47998-48000 dnat to \$VM_IP:47998-48000

	nft add chain ip nat postrouting { type nat hook postrouting priority srcnat \\; policy accept \\; }
	nft add rule ip nat postrouting oifname "$sunshine" masquerade
' >> /var/log/sunshine-hook.log 2>&1 &
EOF
	)" /etc/libvirt/hooks/qemu.d/win-passthrough/started/begin/sunshine.sh

	cmd sudo install -D -m 755 "$(writetext <<EOF
#!/bin/bash

nft -f /etc/nftables.conf
systemctl restart docker.service
EOF
	)" /etc/libvirt/hooks/qemu.d/win-passthrough/stopped/end/sunshine.sh
fi

cmd sudo install -D -m 755 ./virt /usr/local/bin/virt

add_module_temp "plasma-LATE" "$(writetext <<'EOF'
MenuItem {
	text: "Start a VM"
	icon.name: "system-run"
	onTriggered: {
		executable.exec(`bash -c 'virsh start win-passthrough'`)
	}
}
EOF
)"
