#!/usr/bin/env sh
set -e

usage() {
	cat <<EOF
Example: config $DOTFILES_MODULE_NAME --dotfiles ~/dotfiles --host legion
EOF
}
usage_err() {
	if ! [ "$1" = "" ]; then
		echo "$1" >&2
	fi
	usage
	exit 1
}

while [ $# -gt 0 ]; do
	case $1 in
		--host)
			[ "$2" = "" ] && usage_err "Argument not specified"
			host="$2"
			shift
			;;
		--dotfiles)
			[ "$2" = "" ] && usage_err "Argument not specified"
			dotfiles="$2"
			shift
			;;
		*)
			usage_err "Invalid option: $1"
			;;
	esac
	shift
done
[ "$dotfiles" = "" ] && usage_err "Flag not specified"
[ "$host" = "" ] && usage_err "Flag not specified"

newscript archconf <<EOF
#!/usr/bin/env sh

cd $dotfiles
exec \$EDITOR ./configuration-$host.sh
EOF

newscript archupd <<EOF
#!/usr/bin/env sh

usage() {
	echo "Example: \$(basename \$0) [--upgrade|-u] [--module|-m MODULE_NAME]"
}
usage_err() {
	[ "\$1" ] && echo "\$1" >&2
	usage
	exit 1
}

while [ \$# -gt 0 ]; do
	case \$1 in
		--upgrade|-u)
			upgrade=1
			;;
		--module|-m)
			[ "\$2" = "" ] && usage_err "Argument not specified"
			module="\$2"
			shift
			;;
		*)
			usage_err "Invalid option: \$1"
			;;
	esac
	shift
done

[ "\$upgrade" = 1 ] && paru -Syu

cd $dotfiles
[ "\$module" = "" ] && ./configuration-$host.sh || ./configuration-$host.sh --module \$module

if [ "\$upgrade" = 1 ]; then
	sudo mkinitcpio -P
	sudo locale-gen
	sudo bootctl update
	sudo hwclock --systohc
	command -v sbctl >/dev/null 2>&1 && sudo sbctl sign-all
fi
EOF

newscript archexport <<EOF
#!/usr/bin/env sh

echo "\$(paru -Qe | cut -d ' ' -f 1)" > $dotfiles/packages-$host
EOF

newscript archgit <<EOF
#!/usr/bin/env sh

cd $dotfiles
lazygit
EOF

newscript archclean <<EOF
#!/usr/bin/env sh

orphans="\$(paru -Qdtq | xargs)"
if [ ! "\$orphans" = "" ]; then
	paru -Rs --noconfirm \$orphans
fi
yes | paru -Scc
EOF

newscript archedit <<EOF
#!/usr/bin/env sh

if [ "\$EDITOR" = "" ]; then
	EDITOR="nvim"
fi

command="\$(whereis "\$1" | cut -d " " -f 2)"
\$EDITOR "\$command"
EOF
