#!/usr/bin/env sh
set -e

usage() {
	cat <<EOF
Example: config $DOTFILES_MODULE_NAME
EOF
}
usage_err() {
	[ "$1" ] && echo "$1" >&2
	usage
	exit 1
}

while [ $# -gt 0 ]; do
	case $1 in
		--kernel-name)
			[ "$2" = "" ] && usage_err "Argument not specified"
			kernel_name="$2"
			shift
			;;
		*)
			usage_err "Invalid option: $1"
			;;
	esac
	shift
done

[ "$kernel_name" = "" ] && usage_err "Specify --kernel-name argument"

cd "$DOTFILES_MODULE_TEMP"

cmd sudo install -D -m 644 "$(writetext <<EOF
timeout 0
default arch.conf
console-mode keep
EOF
)" /boot/loader/loader.conf
cmd sudo install -D -m 644 "$(writetext <<EOF
title Arch Linux
linux /vmlinuz-$kernel_name
initrd /initramfs-$kernel_name.img
options root=LABEL=arch-root rw nowatchdog $(for f in ./files/*; do cat "$f"; echo " "; done | tr '\n' ' ')
EOF
)" /boot/loader/entries/arch.conf

cmd sudo install -D -m 644 "$(writetext <<EOF
ALL_kver="/boot/vmlinuz-$kernel_name"
PRESETS=('default')
default_image="/boot/initramfs-$kernel_name.img"
EOF
)" /etc/mkinitcpio.d/$kernel_name.preset

cmd sudo install -D -m 644 "$(writetext <<EOF
LABEL=arch-root     	/         	ext4      	rw,relatime	0 1
LABEL=arch-boot     	/boot     	vfat      	rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro	0 2
EOF
)" /etc/fstab
