#!/usr/bin/env sh
set -e

cd "$DOTFILES_MODULE_TEMP"

tmpfile="$(writetext <<EOF
#!/usr/bin/nft -f
# vim:set ts=2 sw=2 et:

flush ruleset

EOF
)"
for file in "./files"/*; do
    [ -f "$file" ] || continue
    cat "$file" >> "$tmpfile"
    printf '\n' >> "$tmpfile"
done

cmd sudo install -D -m 644 "$tmpfile" /etc/nftables.conf

