#!/usr/bin/env sh

# export LD_PRELOAD=""
export DXVK_FILTER_DEVICE_NAME="NVIDIA"
export VKD3D_FILTER_DEVICE_NAME="NVIDIA"

systemctl start scx.service
cpuperf performance
gamemoderun "$@"
cpuperf powersave
systemctl stop scx.service
