#!/usr/bin/env sh
set -e

cmd sudo install -D -m 644 ./nethandler.service /etc/systemd/system/nethandler.service
cmd sudo rm -rf /usr/local/share/nethandler
cmd sudo cp -rf "$DOTFILES_MODULE_SECRETS/nethandler" /usr/local/share
sudo chmod 755 /usr/local/share/nethandler/nethandler
cmd sudo ln -sf /usr/local/share/nethandler/nethandler /usr/local/bin/nethandler
cmd sudo install -D -m 644 ./nftables.conf /etc/nftables.conf
cmd sudo systemctl daemon-reload
cmd sudo systemctl enable nftables.service nethandler.service


add_module_temp "plasma-LATE" "$(writetext <<'EOF'
            MenuItem {
                text: "Toggle Nethandler"
                icon.name: "system-run"
                onTriggered: {
                    executable.exec(`bash -c 'systemctl is-active --quiet "nethandler.service" && systemctl stop nethandler.service || systemctl start nethandler.service'`)
                    updateStatusTimer.start()
                }
            }
            MenuItem {
                text: "Nethandler: " + isNethandlerEnabled
                icon.name: "system-run"
                onTriggered: updateStatus()
            }
EOF
)"

[ -f "$DOTFILES_MODULE_SECRETS/nethandler/hosts" ] && add_module_temp "hosts-LATE" "$DOTFILES_MODULE_SECRETS/nethandler/hosts"

add_module_temp "sysctl-LATE" "$(writetext <<'EOF'
net.netfilter.nf_conntrack_tcp_be_liberal=1
EOF
)"



