#!/usr/bin/env sh
set -e

if ! [ -d ./nethandler ]; then
	echo "Place nethandler directory in nethandler module directory" >&2
	exit 1
fi

cmd sudo install -D -m 644 ./nethandler.service /etc/systemd/system/nethandler.service
cmd sudo rm -rf /usr/local/share/nethandler
cmd sudo cp -rf "$DOTFILES_MODULE_SECRETS/nethandler" /usr/local/share
sudo chmod 755 /usr/local/share/nethandler/nethandler
cmd sudo ln -sf /usr/local/share/nethandler/nethandler /usr/local/bin/nethandler
cmd sudo install -D -m 644 ./nftables.conf /etc/nftables.conf
cmd sudo systemctl daemon-reload
cmd sudo systemctl enable nftables.service nethandler.service

