#!/usr/bin/env -S sh
set -e

usage() {
	cat <<EOF
Example: config $DOTFILES_MODULE_NAME --size 8G
EOF
}
usage_err() {
	if ! [ "$1" = "" ]; then
		echo "$1" >&2
	fi
	usage
	exit 1
}

while [ $# -gt 0 ]; do
	case $1 in
		--size)
			[ "$2" = "" ] && usage_err "Argument not specified"
			size="$2"
			shift
			;;
		*)
			usage_err "Invalid option: $1"
			;;
	esac
	shift
done
[ "$size" = "" ] && usage_err

set +e
if [ ! -f /swapfile ]; then
	cmd sudo mkswap -U clear --size "$size" --file /swapfile
else
	file_size="$(stat -c %s /swapfile)"
	if [ ! "$file_size" = "$(( ${size:0:-1} * 1073741824 ))" ]; then
		if [ "$(swapon --show | grep "/swapfile" | cut -d ' ' -f 1)" = "/swapfile" ]; then
			cmd sudo swapoff /swapfile
		fi
		cmd sudo rm -f /swapfile
		cmd sudo mkswap -U clear --size "$size" --file /swapfile
	fi
fi
	
if ! [ "$(swapon --show | grep "/swapfile" | cut -d ' ' -f 1)" = "/swapfile" ]; then
	cmd sudo swapon /swapfile
fi
set -e

cmd sudo install -D -m 644 "$(writetext <<EOF
[Swap]
What=/swapfile

[Install]
WantedBy=swap.target
EOF
)" /etc/systemd/system/swapfile.swap
cmd sudo systemctl daemon-reload
cmd sudo systemctl enable swapfile.swap
