#!/usr/bin/env sh
set -e

cmd sudo chsh -s /bin/bash "$(whoami)"
cmd sudo chsh -s /bin/bash

cmd sudo rm -rf /etc/fish
cmd sudo install -D -m 755 ./config.fish /etc/fish/config.fish
cmd sudo install -D -m 755 "$(writetext <<'EOF'
[[ $- != *i* ]] && return

if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z ${BASH_EXECUTION_STRING} && ${SHLVL} == 1 ]]
then
	shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=''
	exec fish $LOGIN_OPTION
fi
EOF
)" /etc/bash.bashrc


