#!/usr/bin/env sh
set -e

usage() {
	cat <<EOF
Example: launch-windows
EOF
}
usage_err() {
	[ "$1" ] && echo "$1" >&2
	usage
	exit 1
}

[ "$(whoami)" = "root" ] || usage_err "Insufficient privileges, run as root"

while [ $# -gt 0 ]; do
	case $1 in
		*)
			usage_err "Invalid option: $1"
			;;
	esac
	shift
done

efibootmgr -n $(efibootmgr | grep Windows | cut -c 5-8) && systemctl reboot
