#!/usr/bin/env sh
set -e

cmd rm -f ~/.gitconfig
cmd install -D -m 644 "$(writetext <<'EOF'
[user]
	email = letalbark@gmail.com
	name = Ivan Lifanov
[init]
	defaultBranch = main
[core]
	quotepath = false
[pull]
	rebase = true
EOF
)" ~/.config/git/config

cmd install -D -m 644 ./config.yml ~/.config/gh/config.yml
