#!/usr/bin/env -S sh -e

cmd rm -rf ~/.local/share/konsole
cmd install -Dm644 ./base16-gruvbox-dark-pale.colorscheme ~/.local/share/konsole/base16-gruvbox-dark-pale.colorscheme
cmd install -Dm644 ./dotfiles.profile ~/.local/share/konsole/dotfiles.profile
cmd install -Dm644 ./shortcuts/dotfiles ~/.local/share/konsole/shortcuts/dotfiles

cmd install -Dm644 ./konsolerc ~/.config/konsolerc
cmd install -Dm644 ./konsolesshconfig ~/.config/konsolesshconfig
