#!/usr/bin/env sh
set -e

usage() {
	cat <<EOF
Example: config $DOTFILES_MODULE_NAME
EOF
}
usage_err() {
	if ! [ "$1" = "" ]; then
		echo "$1" >&2
	fi
	usage
	exit 1
}

while [ $# -gt 0 ]; do
	case $1 in
		*)
			usage_err "Invalid option: $1"
			;;
	esac
	shift
done

cmd sudo install -D -m 600 "$DOTFILES_MODULE_SECRETS/secrets" /etc/davfs2/secrets
cmd sudo install -D -m 755 ./yandex-drive /usr/local/bin/yandex-drive
